### ISSUE TITLE
Template PCB does not DC isolate the copper annuluses on the mounting holes.

### ISSUE THREAD

**Issue by pinski1** [SurreyEARS/EARS-PocketQube#1]
According to page 6, PQ60-ICD-2.0 you need to DC isolate the (optional) copper annuluses for the mounting holes with 100nF capacitors to ground.

It may be worth just having 3mm unplated holes so as to not need footprints for 4 100nF capacitors.

**Comment by elstanto** [comment]
Good point! Maybe, will have to have a think.

**Comment by elstanto** [comment]
The new official standard is much more relaxed than the previous proposal. I think we'll use the annuli and leave them attached to the ground plane for now, but with the option to insert the decoupling caps in future.
